# Generated by Django 2.0.3 on 2018-03-13 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='order',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='todolistitem',
            name='order',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
